name: Redd Sales
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.5362
title: Redd Sales
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#636463'
    - '#060706'
    - '#c1c3c5'
    - '#999b9e'
  brandStrength: 1
  lightness: 0.11889151250943542
  saturation: 0.07779883849434555
  rhythmicContrast: 0.6407037223689258
purpose: []
