name: Redd Sales
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: Redd Sales
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ad2e43'
    - '#000000'
    - '#8b8b8b'
    - '#cccccc'
  brandStrength: 1
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 1
purpose: []
